Code variation in echo goodbye

diff --git a/.github/workflows/hello-world.yaml b/.github/workflows/hello-world.yaml
--- a/.github/workflows/hello-world.yaml
+++ b/.github/workflows/hello-world.yaml
@@ -13,9 +13,9 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: failed step
-              run: |
-                - echo "I will fail"
-                - exit 1
+              run:
+                 echo "I will fail"
+                 exit 1
 
             - name: say goodbye
               run: echo "goodbye world"
